### ISSUE TITLE
Zablokowanie możliwości zmerge'owania PR gdy nie są spełnione warunki

### ISSUE THREAD

**Issue by yarpo** [JediSebas/Shapes#13]
Każdy PR musi spełnić odpowiednie warunki, aby można było zmerge'ować kod do `main`.

Warunki:
- unit testy przeszły
- co najmniej 1 członek zespołu zaakceptował kod po code review

**Comment by JediSebas** [comment]
Dodałem branch protection, ale działa dopiero po zmianie widoczności repozytorium na publiczne.
