### ISSUE TITLE
Automatyczne statyczne sprawdzenie jakości kodu

### ISSUE THREAD

**Issue by yarpo** [JediSebas/Shapes#14]
Dodać github action, który automatycznie sprawdzi jakość kodu.

Przykładowe rozwiązania: 
- PMD
- find bug
- sonarcube

Wystarczy jedno.

**Comment by JediSebas** [comment]
Dodałem PMD, ale PR wymaga review. Jeszcze nie wiem, czy PMD jest odpowiednio skonfigurowane.

**Comment by yarpo** [comment]
Sprawdź, jak będzie działać PMD dla PR, które nie mają być merge'owane do `main`. Też powinny się uruchamiać.
Jesli to możliwe, aby bez podawania nazwy brancha, a dla każdego otwartego PR i każdego nowego pusha.

Dodatkowo - sprawdź, czy na pewno potrzebny jest cron job.

**Comment by yarpo** [comment]
Zrobione
